# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e15cd45624e2a8802af94a1e7111b6c786f5d0ed51148e8d801a4d47555ec8b8e0f0da5f84f15402867e77b0602eb5dd844dbdcd3d85e1054fc95a95e7d946c

test:
  secret_key_base: 48783904ff4885ec382580e9fe9135822a0b983acda920a230d9f2b0031224e91f43df8ce7bdea79a5bb38a40f372fc181be5dfb32a6478ec7da35ff08df585d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
